import mongoose from 'mongoose';

const CatSchema = new mongoose.Schema({
  title: {
    type: String,
    default: 'CAT',
  },
  reportid: String,
  had: String,
  number: String,
  emission1: String,
  justify1: String,
  date1: String,
  dateemission1: String,
  type1: String,
  catnumber1: String,
  emission2: String,
  justify2: String,
  date2: String,
  dateemission2: String,
  type2: String,
  catnumber2: String,
  emission3: String,
  justify3: String,
  date3: String,
  dateemission3: String,
  type3: String,
  catnumber3: String,
  emission4: String,
  justify4: String,
  date4: String,
  dateemission4: String,
  type4: String,
  catnumber4: String,
  emission5: String,
  justify5: String,
  date5: String,
  dateemission5: String,
  type5: String,
  catnumber5: String,
  emission6: String,
  justify6: String,
  date6: String,
  dateemission6: String,
  type6: String,
  catnumber6: String,
  emission7: String,
  justify7: String,
  date7: String,
  dateemission7: String,
  type7: String,
  catnumber7: String,
});

export default mongoose.model('CAT', CatSchema);
