import mongoose from 'mongoose';

const EnviromentSchema = new mongoose.Schema({
  title: {
    type: String,
    default: 'Report Ambiental - TSP',
  },
  reportid: String,
  site: String,
  building: String,
  renewableEletricity: String,
  diesel: String,
  gasoline: String,
  querosene: String,
  lgpforklift: String,
  lgpdining: String,
  r134: String,
  r404: String,
  r407a: String,
  r407f: String,
  r422a: String,
  water: String,
  paper: String,
  cardboard: String,
  plastic: String,
  organic: String,
  notRecycle: String,
  metal: String,
  wood: String,
  glass: String,
  lights: String,
  battery: String,
  chemicals: String,
  construction: String,
  greaseTrap: String,
  cessPool: String,
  sewer: String,
  fireExtinguisher: String,
  operationalArea: String,
});

export default mongoose.model('Environment', EnviromentSchema);
